apiVersion: apps/v1
kind: Deployment
metadata:
  name: agis-bot
  labels:
    app: agis-bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agis-bot
  template:
    metadata:
      labels:
        app: agis-bot
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: agis-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: agis-bot-secrets
                  key: DISCORD_TOKEN
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: agis-bot-secrets
                  key: DB_HOST
                  optional: true
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: agis-bot-secrets
                  key: DB_USER
                  optional: true
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agis-bot-secrets
                  key: DB_PASSWORD
                  optional: true
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: agis-bot-secrets
                  key: DB_NAME
                  optional: true
