apiVersion: apps/v1
kind: Deployment
metadata:
  name: agis-bot
  labels:
    app: agis-bot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: agis-bot
  template:
    metadata:
      labels:
        app: agis-bot
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: agis-bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DISCORD_TOKEN
              value: {{ .Values.env.DISCORD_TOKEN | quote }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST | quote }}
