apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agis-bot
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: agis-bot-development.euw.wtgg.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agis-bot-metrics
                port:
                  number: 9090
