image:
  repository: ghcr.io/wethegamers/agis-bot
  tag: dev

deploymentAnnotations:
  linkerd.io/inject: "enabled"

imagePullSecrets:
  - name: docker-config

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
    - host: agis-bot-development.euw.wtgg.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: agis-bot-development-tls
      hosts:
        - agis-bot-development.euw.wtgg.org

agis-bot:
  host: https://agis-bot-development.euw.wtgg.org/api
  console: https://kubefirst.euw.wtgg.org

vaultMountPoint: kubefirst
vaultSecretPath: development/agis-bot
clusterSecretStoreName: vault-kv-secret
configs:
  configOne: development-config-one
  configTwo: development-config-two

originIssuerIsEnabled: false
